services:
  postgres:
    image: postgres:15
    container_name: mastermind_db
    restart: always
    environment:
      POSTGRES_USER: mastermind_user
      POSTGRES_PASSWORD: mastermind_password
      POSTGRES_DB: mastermind
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

# liga o container 
# docker-compose up -d ou docker compose up -d

# consulta status do docker
# docker-compose ps ou docker compose ps

# desliga banco
# docker-compose down ou docker compose down

# caso queira fazer consulta de dados no banco roda o comando do prisma studio
# npx prisma studio